### PR TITLE
Update readme 

### PR DESCRIPTION
**Pull request by scottcwilson**
The old project website http://xajax-project.org is now being used by spammers, so it has been removed from the README file

### CODE REVIEW

**Comment by manubittencourt** [comment]
Is the project dead? What is the new website?

**Comment by scottcwilson** [comment]
There is no new website.

**Comment by feuzeu** [comment]
There's a fork at https://www.jaxon-php.org

**Comment by scottcwilson** [comment]
I just generally use jQuery now.  I have some legacy xajax code that I still maintain though, so I keep an eye out for issues.

**Pull request closed without merging**
