### PR TITLE
Add xajax.inc.php to file-based autoloading

### PR DESCRIPTION
**Pull request by holtkamp**
This file contains / defines some specific functionality. Check https://getcomposer.org/doc/04-schema.md#files

### CODE REVIEW

**Comment by frecervantes** [comment]
hi, may you help please... this error started when I update my xajax ver. 0.5 with the package of xajax-patch-php7.
overwriting all the existing files and copying the composer.json and .gitignore in the root of my project.

localhost says
Error: the xajax.debug Javascript component could not be included.
perhaps the URL is incorrect?
URL: ./xajax/xajax_js/xajax_js/xajax_debug.js

I tryied to solve this issue creating a xajax_js folder inside the xajax_js existing folder and copied the files from the parent directory too, but it did not work.
whst's wrong ? everything works perfectly under 0.5 version.

hope i explained well myself.

thanks in advance.

**Comment by holtkamp** [comment]
@frecervantes this looks a lot like this: https://github.com/Xajax/Xajax/pull/47#issuecomment-597352068

**Comment by frecervantes** [comment]
Is there any error free link or repository with a library ready for xajax php7.x to download and install? like version 0.5. This easy way to get started was the main reason for the rapid growth of the community, and it would  be helpful at this time.

thank you for your patience

**Comment by holtkamp** [comment]
@frecervantes you can "+1" this pull request: https://github.com/Xajax/Xajax/pull/47#issuecomment-597352068

**Pull request merged**
